#!/bin/sh

# Start up a tmux session with docker + django server.

SESSION=cleo-server
WINDOW=work
APP_DIRECTORY=~/code/cleo-app
BACKEND_DIRECTORY=~/code/cleo-backend

tmux new -s $SESSION -d

tmux rename-window -t $SESSION $WINDOW
tmux split-window -t $SESSION -h
tmux split-window -t $SESSION -v

tmux send-keys -t $SESSION.0 "cd $BACKEND_DIRECTORY" Enter
tmux send-keys -t $SESSION.1 "cd $BACKEND_DIRECTORY; docker-compose up" Enter
tmux send-keys -t $SESSION.2 "cd $BACKEND_DIRECTORY; sleep 2; cleo-server" Enter

tmux attach -t $SESSION.0
